name: Credentials Scan

on:
  pull_request:
    branches: [master, test, dev]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  credentials-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Display python version
        run: python -c "import sys; print(sys.version)"

      - name: Cache python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          key: ${{ runner.os }}-pip

      - name: Install requirements
        run: |
          pip install trufflehog3

      - name: Scan with trufflehog3
        id: scan
        run: |
          trufflehog3 -v --no-history --config .github/.trufflehog3.yml --format json --output trufflehog_report.json

      - name: Generate HTML from json report
        if: failure()
        run: |
          trufflehog3 -R trufflehog_report.json --output trufflehog_report.html

      - name: Upload HTML report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: Security Scan Report
          path: trufflehog_report.html
          retention-days: 7
